version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"  # Everything served from here
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./frontend/build:/app/frontend/build  # Mount built frontend into backend

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=${LOCAL_DB_NAME}
      - POSTGRES_USER=${LOCAL_DB_USER}
      - POSTGRES_PASSWORD=${LOCAL_DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: